install:
  - npm install -g polymer-cli
  - polymer install --variants
before_script:
  - polymer lint
dist: trusty
sudo: 'false'
node_js: stable
script:
  - polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - node_modules
env:
  global: []
